sudo: required

language: generic

services:
  - docker

before_install:
  - echo "Start creating an image with dockerfile"
  - docker build -t kstyle0710/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kstyle0710/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  edge: true
  region: 'us-east-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-068547093364'
  bucket-path: 'docker-react'
  on:
    branch: master
access_key_id: $aws_access_key
secret_access_key: $aws_secret_key

after_success:
  - echo "Test Success"
